# Generated by Django 2.1.15 on 2020-09-25 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='location/')),
                ('address', models.CharField(max_length=150)),
                ('array', jsonfield.fields.JSONField(default=dict)),
                ('ndim', models.IntegerField(default=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationRated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationindx', models.IntegerField(default=-1)),
                ('value', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendationsystem.LocationData')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', jsonfield.fields.JSONField(default=dict)),
                ('arrayratedlocationsindxs', jsonfield.fields.JSONField(default=dict)),
                ('name', models.CharField(max_length=1000)),
                ('lastrecs', jsonfield.fields.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='locationrated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedlocations', to='recommendationsystem.UserProfile'),
        ),
    ]
